# Generated by Django 5.2.10 on 2026-01-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_questionbank_question_type_examquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Múltipla Escolha'), ('ESSAY', 'Dissertativa'), ('TRUE_FALSE', 'Verdadeiro/Falso'), ('FILL_THE_BLANK', 'Preencher Lacuna')], default='MULTIPLE_CHOICE', max_length=20),
        ),
    ]
