# Generated by Django 5.2.10 on 2026-01-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_choice_quiz_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Is this a live stream?'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL', null=True),
        ),
    ]
