# Generated by Django 5.2.10 on 2026-02-10 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_jetwallet_jettransaction_delete_userpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (JetCredits)')),
                ('category', models.CharField(choices=[('certificate', 'Certificado'), ('mentorship', 'Mentoria'), ('discount', 'Desconto'), ('feature', 'Funcionalidade Premium'), ('merchandise', 'Merchandise')], default='feature', max_length=20)),
                ('icon', models.CharField(default='bi-gift', help_text='Bootstrap Icon class', max_length=30)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=-1, help_text='-1 = ilimitado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='jetwallet',
            name='level',
            field=models.CharField(default='Iniciante', max_length=20),
        ),
        migrations.AddField(
            model_name='jetwallet',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Ganho'),
        ),
        migrations.AddField(
            model_name='jetwallet',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Gasto'),
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='gamification.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
